### ISSUE TITLE
Need a brief description for --scorer_model_dir

### ISSUE THREAD

**Issue by LoFiApostasy** [s1dlx/sd-webui-bayesian-merger#6]
First off Awesome work! Its lacking a quick sentence about how it deals with the scorer models.
Not sure if it tries all models or can even load more than one.
I copied all the models from the  https://github.com/Xerxemi/sdweb-auto-MBW  plugin.  Are there others that work with it is that even a good idea? Im assuming this option is not needed if I just drop models into that folder??

Thanks for all your hard work!

**Comment by s1dlx** [comment]
@LoFiApostasy hello!

Yes, that section needs more explanation. Truth is at the moment only Chad scorer is supported. Not because it’s the best but only because I have to implement a generic scorer yet. Eventually it will work as you say, just dump the models in that folder and select the one you want to use from cli. 

I’m working on it, stay tuned!

**Comment by saftle** [comment]
Where can I find the Chad Scorer that is supported?

**Comment by s1dlx** [comment]
> Where can I find the Chad Scorer that is supported?

For now it’s hard coded here
https://github.com/s1dlx/sd-webui-bayesian-merger/blob/39f4fa25ab07c8f0187e1d51defe53a925b7a449/sd_webui_bayesian_merger/scorer.py#L42

**Comment by s1dlx** [comment]
@LoFiApostasy #12 closes this
